spring:
  application:
    name: bucketeer
  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: false
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB

server:
  port: 8080

bucketeer:
  version: "0.7.7"
  release-date: "2026-09-08"