spring:
  application:
    name: bucketeer
  messages:
    basename: messages
    encoding: UTF-8

server:
  port: 8080

bucketeer:
  version: "0.3.2"
  release-date: "2026-07-21"
  snapshots:
    retention-days: 30