spring:
  application:
    name: bucketeer
  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: false

server:
  port: 8080

bucketeer:
  version: "0.7.0"
  release-date: "2026-08-08"